from enum import Enum


class BatchElementType(str, Enum):
    ORIGINAL_FOLD_TEXT_CLOZE = 'ORIGINAL_FOLD_TEXT_CLOZE'
    ORIGINAL_FOLD_VISUAL_CLOZE = 'ORIGINAL_FOLD_VISUAL_CLOZE'
    ORIGINAL_FOLD_CHAR_COHERENCE = 'ORIGINAL_FOLD_CHAR_COHERENCE'
    CUSTOM_JSON = 'CUSTOM_JSON'
