_target_: src.datamodules.dcm_detection_datamodule.DCMDetectionDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: [0, -70, -35]
img_dims_hw: [512, 512]
batch_size: 64
num_workers: 5
pin_memory: False